services:
  nestapp:
    image: gastongonzalez17/vibra-oeste:latest # Usa la imagen de Docker Hub
    ports:
      - "3002:3001" # Mapea el puerto 3001 local al puerto 3000 del contenedor
    env_file:
      - .env # Variables de entorno desde el archivo .env
    depends_on:
      - postgresdb # Asegura que PostgreSQL esté iniciado antes
    restart: always # Reinicia automáticamente si se detiene
    networks:
      - app_network 

  postgresdb:
    image: postgres:13 # Usa una imagen estable de PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data # Volumen persistente para los datos
    # env_file:
    #   - .env.development # Variables de entorno desde el archivo .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bocacapo
      POSTGRES_DB: vibraoeste
    ports:
      - "5432:5432" # Expon el puerto de PostgreSQL
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network: