name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gastongonzalez17
          password: dckr_pat_AxUKP7GbFJMfBcUKAzN1KvG-umo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./back
          file: Dockerfile
          push: true
          tags: gastongonzalez17/ecommerce:latest
